name: adhoc_plugin_example
description: Demonstrates how to use the adhoc_plugin plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adhoc_plugin:
    path: ../
  analyzer_plugin: ^0.6.0
  cupertino_icons: ^1.0.3
  file_picker: ^3.0.1
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true