name: adhoclibrary_example
description: Demonstrates how to use the adhoclibrary plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adhoclibrary:
    path: ../
  cupertino_icons: ^1.0.0
  file_picker: 2.1.7
  flutter_document_picker: ^4.0.1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

