name: adhoc_plugin
description: Flutter plugin that allows creating and managing a mobile (Android only) ad hoc network
version: 1.0.0
author: Thai Dinh Le <Thai.Dinh.Le.pro@gmail.com>
homepage: https://github.com/thai-dinh/adhoc_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble: ^2.7.3
  json_annotation: ^4.0.1
  meta: ^1.3.0
  uuid: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2
  json_serializable: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.montefiore.thaidinhle.adhoc_plugin
        pluginClass: AdhocPlugin
