name: adhoclibrary
description: Adhoclibrary is a library which allows to create and manage ad hoc connections on Android mobile devices
version: 0.1.0
author: Thai Dinh Le <Thai.Le@student.uliege.be>
homepage: https://github.com/thai-dinh/AdHocLib

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble: ^2.7.3
  json_annotation: ^4.0.0
  location: ^3.2.4
  meta: ^1.3.0
  permission_handler: ^5.1.0+2
  uuid: ^3.0.1

  flutter_wifi_p2p:
    git:
      url: https://github.com/thai-dinh/flutter_wifi_p2p

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.5
  json_serializable: ^4.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.montefiore.thaidinhle.adhoclibrary
        pluginClass: AdHocPlugin
