name: adhoclibrary
description: adhoclibrary is a library which allows to create and manage ad hoc connections on Android mobile devices
version: 0.1.0
author: Thai Dinh Le <Thai.Le@student.uliege.be>
homepage: https://github.com/thai-dinh/AdHocLib

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.montefiore.thaidinhle.adhoclibrary
        pluginClass: AdhocPlugin
