name: adhoc_plugin
description: Flutter plugin that allows creating and managing a mobile (Android only) ad hoc network
version: 1.0.1
author: Thai Dinh Le <Thai.Dinh.Le.pro@gmail.com>
homepage: https://github.com/thai-dinh/adhoc_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  archive: ^3.1.2
  cryptography: ^2.0.1
  flutter_reactive_ble: ^3.1.0
  json_annotation: ^4.0.1
  meta: ^1.3.0
  pointycastle: ^3.0.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.montefiore.thaidinhle.adhoc_plugin
        pluginClass: AdhocPlugin
